CREATE TABLE raza(
    id_raza INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_raza VARCHAR2(20),
    --p.k.
    PRIMARY KEY (id_raza)

);


CREATE TABLE clase(
    id_clase INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_clase VARCHAR2(20),
    --p.k.
    PRIMARY KEY (id_clase)

);


CREATE TABLE tipo_danno(
    id_tipo_danno INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_danno VARCHAR2(10),
    --p.k.
    PRIMARY KEY (id_tipo_danno)
);


CREATE TABLE tipo_objeto(
    id_tipo_objeto INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_tipo_objeto varchar2(20),
    --p.k.
    PRIMARY KEY (id_tipo_objeto)
);


CREATE TABLE atributos_logicos(
    id_logica INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    fuerza INT NOT NULL,
    inteligencia INT NOT NULL,
    destreza INT NOT NULL,
    fe INT NOT NULL,
    vida INT NOT NULL,
    velocidad INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_logica)
);


CREATE TABLE atributos_visuales(
    id_visual INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_pelo varchar2(20),
    tipo_ojos varchar2(20),
    tipo_piel varchar2(20),
    altura INT NOT NULL,
    complexion varchar2(20),
    --p.k.
    PRIMARY KEY (id_visual)
);


CREATE TABLE bioma(
    id_bioma INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_bioma VARCHAR2(10),
    --p.k.
    PRIMARY KEY (id_bioma)
);


CREATE TABLE nivel(
    nivel INT NOT NULL,
    exp_siguiente_nivel INT,
    nivel_anterior INT,
    --p.k.
    PRIMARY KEY (nivel),
    --f.k.
    CONSTRAINT fk_nivel_nivel FOREIGN KEY (nivel_anterior) REFERENCES nivel(nivel)
);


CREATE TABLE habilidad(
    id_habilidad INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_tipo_danno INT NOT NULL,
    cantidad_danno INT NOT NULL,
    coste INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_habilidad),
    --f.k.
    CONSTRAINT fk_habilidad_tipo_danno FOREIGN KEY (id_tipo_danno) REFERENCES tipo_danno(id_tipo_danno)
);


CREATE TABLE aprendizaje(
    id_aprendizaje INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_habilidad INT NOT NULL,
    id_clase INT NOT NULL,
    nivel_aprendizaje INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_aprendizaje),
    --f.k.
    CONSTRAINT fk_aprendizaje_clase FOREIGN KEY (id_clase) REFERENCES clase(id_clase),
    CONSTRAINT fk_aprendizaje_habilidad FOREIGN KEY (id_habilidad) REFERENCES habilidad(id_habilidad)
);


CREATE TABLE localizacion(
    id_localizacion INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    localizacion_anterior INT, 
    id_bioma INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_localizacion),
    
    CONSTRAINT fk_localizacion_localizacion FOREIGN KEY (localizacion_anterior) REFERENCES localizacion(id_localizacion),
    CONSTRAINT fk_localizacion_bioma FOREIGN KEY (id_bioma) REFERENCES bioma(id_bioma)
);


CREATE TABLE personaje(
    id_personaje INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    genero VARCHAR2(20),
    oro INT DEFAULT 0,
    id_visual INT,
    id_logica INT,
    nivel INT,
    id_localizacion INT,
    --p.k.
    PRIMARY KEY (id_personaje),
    --relaciones
    CONSTRAINT fk_personaje_atributos_visuales FOREIGN KEY (id_visual) REFERENCES atributos_visuales(id_visual),
    CONSTRAINT fk_personaje_atributos_logicos FOREIGN KEY (id_logica) REFERENCES atributos_logicos(id_logica),
    CONSTRAINT fk_personaje_nivel FOREIGN KEY (nivel) REFERENCES nivel(nivel),
    CONSTRAINT fk_personaje_localizacion FOREIGN KEY (id_localizacion) REFERENCES localizacion(id_localizacion)

);


CREATE TABLE objeto(
    id_objeto INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_objeto varchar2(10),
    cantidad_danno INT NOT NULL,
    id_tipo_danno INT NOT NULL,
    id_tipo_objeto INT NOT NULL,
    id_mision INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_objeto),
    --f.k.
    CONSTRAINT fk_objeto_tipo_danno FOREIGN KEY (id_tipo_danno) REFERENCES tipo_danno(id_tipo_danno),
    CONSTRAINT fk_objeto_tipo_objeto FOREIGN KEY (id_tipo_objeto) REFERENCES tipo_objeto(id_tipo_objeto)
);


CREATE TABLE enemigo(
    id_personaje INT NOT NULL,
    tipo_enemigo varchar2(20),
    --p.k.
    PRIMARY KEY (id_personaje),
    --f.k.
    CONSTRAINT fk_enemigo_personaje FOREIGN KEY (id_personaje) REFERENCES personaje(id_personaje) ON DELETE CASCADE
);

CREATE TABLE protagonista(
    id_personaje INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_personaje),
    --k.k
    CONSTRAINT fk_protagonista_personaje FOREIGN KEY (id_personaje) REFERENCES personaje(id_personaje) ON DELETE CASCADE
);

CREATE TABLE aliado(
    id_personaje INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_personaje), 
    CONSTRAINT fk_aliado_personaje FOREIGN KEY (id_personaje) REFERENCES personaje(id_personaje) ON DELETE CASCADE
    );


CREATE TABLE combinacion (
    id_raza INT NOT NULL,
    id_clase INT NOT NULL,
    id_personaje INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_raza, id_clase, id_personaje),
    --relaciones
    CONSTRAINT fk_combinacion_raza FOREIGN KEY (id_raza) REFERENCES raza(id_raza),
    CONSTRAINT fk_combinacion_clase FOREIGN KEY (id_clase) REFERENCES clase(id_clase),
    CONSTRAINT fk_combinacion_personaje FOREIGN KEY (id_personaje) REFERENCES personaje(id_personaje)

);

CREATE TABLE objeto_localizacion(
    id_obj_localizacion INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_objeto INT NOT NULL,
    id_localizacion INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_obj_localizacion),
    --f.k.
    CONSTRAINT fk_objeto_localizacion_objeto FOREIGN KEY (id_objeto) REFERENCES objeto(id_objeto),
    CONSTRAINT fk_objeto_localizacion_localizacion FOREIGN KEY (id_localizacion) REFERENCES localizacion(id_localizacion)
    

);


CREATE TABLE drop_objeto(
    id_drop INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_personaje INT NOT NULL,
    id_objeto INT NOT NULL,
    posibilidad INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_drop),
    --f.k.
    CONSTRAINT fk_drop_objeto_personaje FOREIGN KEY (id_personaje) REFERENCES personaje(id_personaje),
    CONSTRAINT fk_drop_objeto_objeto FOREIGN KEY (id_objeto) REFERENCES objeto (id_objeto)
);


CREATE TABLE mision (
    id_mision INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_personaje INT NOT NULL,
    mision_anterior INT,
    id_objeto INT,
    --p.k.
    PRIMARY KEY (id_mision),
    --f.k.
    CONSTRAINT fk_mision_mision FOREIGN KEY (mision_anterior)REFERENCES mision(id_mision),
    CONSTRAINT fk_mision_objeto FOREIGN KEY (id_objeto) REFERENCES objeto(id_objeto),
    CONSTRAINT fk_mision_aliado FOREIGN KEY (id_personaje) REFERENCES aliado(id_personaje)
);


CREATE TABLE objetivo(
    id_objetivo INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    descripcion_objetivo varchar2(200),
    id_mision INT NOT NULL,
    --p.k.
    PRIMARY KEY (id_objetivo),
    --f.k.
    CONSTRAINT fk_id_objetivo_mision FOREIGN KEY (id_mision) REFERENCES mision(id_mision)
);