--DROPS
DROP TABLE ACCIDENT_VEHICLE;
DROP TABLE MULTA;
DROP TABLE ACCIDENT;
DROP TABLE VEHICLE;
DROP TABLE PERSONA;

CREATE TABLE PERSONA (
    DNI VARCHAR2(9) PRIMARY KEY,
    NOM VARCHAR2(50),
    LLINATGES VARCHAR2(100),
    ADRECA VARCHAR2(100),
    CODI_POSTAL VARCHAR(5) CHECK (CODI_POSTAL != '07430'),
    TELEFON NUMBER(9),
    DATA_ALTA DATE
);

CREATE TABLE VEHICLE (
    MATRICULA VARCHAR2(7) PRIMARY KEY,
    MARCA VARCHAR2(30),
    MODEL_VEHICLE VARCHAR2(30),
    CHECK (SUBSTR(MODEL_VEHICLE, 1, 4) != 'RB19'),
    DNI VARCHAR2(9) NOT NULL,
    FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE MULTA (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    DATA_I_HORA DATE,
    LLOC VARCHAR2(100),
    IMPORT_MULTA NUMBER(10,2) CHECK (IMPORT_MULTA >= 100.00),
    MATRICULA_VEHICLE VARCHAR2(7),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA)
);

CREATE TABLE ACCIDENT (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    LLOC VARCHAR2(100),
    DATA_I_HORA DATE
);

CREATE TABLE ACCIDENT_VEHICLE (
    MATRICULA_VEHICLE VARCHAR2(7),
    CODI_ACCIDENT NUMBER NOT NULL,
    INFORME_PARTICIPACIO VARCHAR2(500),
    PRIMARY KEY (MATRICULA_VEHICLE, CODI_ACCIDENT),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA),
    FOREIGN KEY (CODI_ACCIDENT) REFERENCES ACCIDENT(CODI)
);

-- INSERT
-- PERSONES
INSERT INTO PERSONA (DNI, NOM, LLINATGES, ADRECA, CODI_POSTAL, TELEFON, DATA_ALTA) 
VALUES ('12345678A', 'Joan', 'Pep', 'Carrer Major', '00001', 600000001, TO_DATE('01-01-2024', 'DD-MM-YYYY'));

INSERT INTO PERSONA (DNI, NOM, LLINATGES, ADRECA, CODI_POSTAL, TELEFON, DATA_ALTA) 
VALUES ('12345678B', 'Maria', 'Pons', 'Carrer Menor', '00002', 600000002, TO_DATE('01-01-2025', 'DD-MM-YYYY'));

-- VEHICLES
INSERT INTO VEHICLE (MATRICULA, MARCA, MODEL_VEHICLE, DNI) 
VALUES ('1234ABC', 'Toyota', 'Corolla', '12345678A');

INSERT INTO VEHICLE (MATRICULA, MARCA, MODEL_VEHICLE, DNI) 
VALUES ('1234DEF', 'Seat', 'Ibiza', '12345678A');

INSERT INTO VEHICLE (MATRICULA, MARCA, MODEL_VEHICLE, DNI) 
VALUES ('9999ZZZ', 'Ford', 'Focus', '12345678B');

-- MULTA
INSERT INTO MULTA (DATA_I_HORA, LLOC, IMPORT_MULTA, MATRICULA_VEHICLE) 
VALUES (CURRENT_TIMESTAMP, 'Avinguda Gabriel Alomar', 150.00, '1234ABC');

-- ACCIDENT
INSERT INTO ACCIDENT (LLOC, DATA_I_HORA) 
VALUES ('Rotonda de Son Rapinya', SYSDATE);

-- 2 VEHICLES EN EL ACCIDENTE 
INSERT INTO ACCIDENT_VEHICLE (MATRICULA_VEHICLE, CODI_ACCIDENT, INFORME_PARTICIPACIO) 
VALUES ('1234ABC', 1, 'Conductor borracho.');

INSERT INTO ACCIDENT_VEHICLE (MATRICULA_VEHICLE, CODI_ACCIDENT, INFORME_PARTICIPACIO) 
VALUES ('9999ZZZ', 1, 'No lleva baliza.');

-- modificaciones
ALTER TABLE MULTA ADD data_pagament DATE;
ALTER TABLE ACCIDENT_VEHICLE MODIFY informe_participacio VARCHAR2(2000);
ALTER TABLE PERSONA DROP COLUMN DATA_ALTA;
UPDATE PERSONA SET NOM = 'Pere Pep' WHERE DNI = '12345678A';
DELETE FROM MULTA WHERE MATRICULA_VEHICLE = '1234ABC';


