create table raza (
   id_raza     int generated by default on null as identity,
   nombre_raza varchar2(20),
    --p.k.
   primary key ( id_raza )
);


create table clase (
   id_clase     int generated by default on null as identity,
   nombre_clase varchar2(20),
    --p.k.
   primary key ( id_clase )
);


create table tipo_danno (
   id_tipo_danno int generated by default on null as identity,
   nombre_danno  varchar2(10),
    --p.k.
   primary key ( id_tipo_danno )
);


create table tipo_objeto (
   id_tipo_objeto     int generated by default on null as identity,
   nombre_tipo_objeto varchar2(20),
    --p.k.
   primary key ( id_tipo_objeto )
);


create table atributos_logicos (
   id_logica    int generated by default on null as identity,
   fuerza       int not null check ( fuerza >= 0 ),
   inteligencia int not null check ( inteligencia >= 0 ),
   destreza     int not null check ( destreza >= 0 ),
   fe           int not null check ( fe >= 0 ),
   vida         int not null check ( vida > 0 ),
   velocidad    int not null check ( velocidad >= 0 ),
    --p.k.
   primary key ( id_logica )
);


create table atributos_visuales (
   id_visual  int generated by default on null as identity,
   tipo_pelo  varchar2(20),
   tipo_ojos  varchar2(20),
   tipo_piel  varchar2(20),
   altura     int not null,
   complexion varchar2(20),
    --p.k.
   primary key ( id_visual )
);


create table bioma (
   id_bioma     int generated by default on null as identity,
   nombre_bioma varchar2(10),
    --p.k.
   primary key ( id_bioma )
);


create table nivel (
   nivel               int not null,
   exp_siguiente_nivel int,
   nivel_anterior      int,
    --p.k.
   primary key ( nivel ),
    --f.k.
   constraint fk_nivel_nivel foreign key ( nivel_anterior )
      references nivel ( nivel )
);


create table habilidad (
   id_habilidad   int generated by default on null as identity,
   id_tipo_danno  int not null,
   cantidad_danno int not null,
   coste          int not null,
    --p.k.
   primary key ( id_habilidad ),
    --f.k.
   constraint fk_habilidad_tipo_danno foreign key ( id_tipo_danno )
      references tipo_danno ( id_tipo_danno )
);


create table aprendizaje (
   id_aprendizaje    int generated by default on null as identity,
   id_habilidad      int not null,
   id_clase          int not null,
   nivel_aprendizaje int not null,
    --p.k.
   primary key ( id_aprendizaje ),
    --f.k.
   constraint fk_aprendizaje_clase foreign key ( id_clase )
      references clase ( id_clase ),
   constraint fk_aprendizaje_habilidad foreign key ( id_habilidad )
      references habilidad ( id_habilidad )
);


create table localizacion (
   id_localizacion       int generated by default on null as identity,
   localizacion_anterior int,
   id_bioma              int not null,
    --p.k.
   primary key ( id_localizacion ),
   constraint fk_localizacion_localizacion foreign key ( localizacion_anterior )
      references localizacion ( id_localizacion ),
   constraint fk_localizacion_bioma foreign key ( id_bioma )
      references bioma ( id_bioma )
);


create table personaje (
   id_personaje    int generated by default on null as identity,
   nombre          varchar2(100) not null,
   genero          varchar2(20),
   oro             int default 0,
   id_visual       int,
   id_logica       int,
   nivel           int,
   id_localizacion int,
    --p.k.
   primary key ( id_personaje ),
    --relaciones
   constraint fk_personaje_atributos_visuales foreign key ( id_visual )
      references atributos_visuales ( id_visual ),
   constraint fk_personaje_atributos_logicos foreign key ( id_logica )
      references atributos_logicos ( id_logica ),
   constraint fk_personaje_nivel foreign key ( nivel )
      references nivel ( nivel ),
   constraint fk_personaje_localizacion foreign key ( id_localizacion )
      references localizacion ( id_localizacion )
);


create table objeto (
   id_objeto      int generated by default on null as identity,
   nombre_objeto  varchar2(10),
   cantidad_danno int not null,
   id_tipo_danno  int not null,
   id_tipo_objeto int not null,
   id_mision      int,
    --p.k.
   primary key ( id_objeto ),
    --f.k.
   constraint fk_objeto_tipo_danno foreign key ( id_tipo_danno )
      references tipo_danno ( id_tipo_danno ),
   constraint fk_objeto_tipo_objeto foreign key ( id_tipo_objeto )
      references tipo_objeto ( id_tipo_objeto )
);


create table enemigo (
   id_personaje int not null,
   tipo_enemigo varchar2(20),
    --p.k.
   primary key ( id_personaje ),
    --f.k.
   constraint fk_enemigo_personaje foreign key ( id_personaje )
      references personaje ( id_personaje )
         on delete cascade
);

create table protagonista (
   id_personaje int not null,
    --p.k.
   primary key ( id_personaje ),
    --k.k
   constraint fk_protagonista_personaje foreign key ( id_personaje )
      references personaje ( id_personaje )
         on delete cascade
);

create table aliado (
   id_personaje int not null,
    --p.k.
   primary key ( id_personaje ),
   constraint fk_aliado_personaje foreign key ( id_personaje )
      references personaje ( id_personaje )
         on delete cascade
);


create table combinacion (
   id_raza      int not null,
   id_clase     int not null,
   id_personaje int not null,
    --p.k.
   primary key ( id_raza,
                 id_clase,
                 id_personaje ),
    --relaciones
   constraint fk_combinacion_raza foreign key ( id_raza )
      references raza ( id_raza ),
   constraint fk_combinacion_clase foreign key ( id_clase )
      references clase ( id_clase ),
   constraint fk_combinacion_personaje foreign key ( id_personaje )
      references personaje ( id_personaje )
);

create table objeto_localizacion (
   id_obj_localizacion int generated by default on null as identity,
   id_objeto           int not null,
   id_localizacion     int not null,
    --p.k.
   primary key ( id_obj_localizacion ),
    --f.k.
   constraint fk_objeto_localizacion_objeto foreign key ( id_objeto )
      references objeto ( id_objeto ),
   constraint fk_objeto_localizacion_localizacion foreign key ( id_localizacion )
      references localizacion ( id_localizacion )
);


create table drop_objeto (
   id_drop      int generated by default on null as identity,
   id_personaje int not null,
   id_objeto    int not null,
   posibilidad  int not null,
    --p.k.
   primary key ( id_drop ),
    --f.k.
   constraint fk_drop_objeto_personaje foreign key ( id_personaje )
      references personaje ( id_personaje ),
   constraint fk_drop_objeto_objeto foreign key ( id_objeto )
      references objeto ( id_objeto )
);


create table mision (
   id_mision       int generated by default on null as identity,
   id_personaje    int not null,
   mision_anterior int,
   id_objeto       int,
    --p.k.
   primary key ( id_mision ),
    --f.k.
   constraint fk_mision_mision foreign key ( mision_anterior )
      references mision ( id_mision ),
   constraint fk_mision_objeto foreign key ( id_objeto )
      references objeto ( id_objeto ),
   constraint fk_mision_aliado foreign key ( id_personaje )
      references aliado ( id_personaje )
);


create table objetivo (
   id_objetivo          int generated by default on null as identity,
   descripcion_objetivo varchar2(200),
   id_mision            int not null,
    --p.k.
   primary key ( id_objetivo ),
    --f.k.
   constraint fk_id_objetivo_mision foreign key ( id_mision )
      references mision ( id_mision )
);